# Generated by Django 2.2.3 on 2019-08-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, unique=True, upload_to='music')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('file_mtime', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('bitrate_mode', models.TextField(blank=True, null=True)),
                ('finger_print', models.TextField(blank=True, null=True)),
                ('traktor_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'track',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TraktorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_file', models.TextField()),
                ('audio_id', models.TextField(blank=True, null=True)),
                ('artist', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('dir', models.TextField()),
                ('file', models.TextField()),
                ('ranking', models.TextField(blank=True, null=True)),
                ('bpm', models.TextField(blank=True, null=True)),
                ('bitrate', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('playcount', models.IntegerField(blank=True, null=True)),
                ('playtime', models.TextField(blank=True, null=True)),
                ('playtime_float', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('xml_id', models.IntegerField()),
                ('xml', models.TextField()),
                ('modified_date', models.DateTimeField(null=True)),
                ('import_date', models.DateField(null=True)),
                ('last_played', models.DateField(null=True)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traktorinfo_set', to='tracks.Track')),
            ],
            options={
                'db_table': 'track_traktor_info',
                'managed': True,
                'unique_together': {('xml_id', 'collection_file')},
            },
        ),
        migrations.CreateModel(
            name='TrackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('desc', models.TextField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tracks.Track')),
            ],
            options={
                'db_table': 'track_image',
                'managed': True,
                'unique_together': {('track', 'desc')},
            },
        ),
    ]
