# Generated by Django 2.2.7 on 2019-11-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
