# Generated by Django 2.2.3 on 2019-08-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traktorinfo',
            name='import_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traktorinfo',
            name='last_played',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traktorinfo',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
